Metrics/LineLength:
  Max: 120
Documentation:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Max: 75
Style/FormatStringToken:
  Enabled: false
Metrics/ClassLength:
  Max: 130