sudo: required

language: generic

services:
  - docker

addons:
  hosts:
    - local.host
    - msk.local.host
    - spb.local.host

env:
  global:
    - ENV=travis
    - NET=host
    - IMAGE=subscity
    - IMAGE_NAME=${DOCKER_USERNAME}/${IMAGE}:${TRAVIS_BRANCH}

before_script:
  - sudo service mysql stop
  - sudo rm -rf /var/lib/mysql
  - gem install rubocop

script:
  - rubocop
  - docker pull ${IMAGE_NAME} || echo "couldn't pull docker cache"
  - ./scripts/build.sh --cache-from ${IMAGE_NAME}
  - docker-compose up -d
  - until nc -z 127.0.0.1 3306; do sleep 3; echo "Waiting for DB to come up..."; done
  - docker exec -it subscity-app /bin/bash -c "cd /subscity && ./test"
  - docker exec -it subscity-app /bin/bash -c "cd /subscity && rake ar:schema:load && padrino run db/seed_cities.rb"
  - docker exec -it subscity-app /bin/bash -c "cd /subscity/tasks && rake clear_cache"

  - curl -sI 'http://local.host:3000' | grep -q 'https://msk.local.host/'
  - curl -sL 'http://msk.local.host:3000' | grep -q 'vk.com/subscity_msk'
  - curl -sL 'http://msk.local.host:3000/stylesheets/design.css' | grep -q 'color'
  - curl -sL 'http://spb.local.host:3000/javascripts/default.min.js' | grep -q 'function'

  - curl -sI 'http://msk.local.host/aaa?b=1' | grep -q 'https://msk.local.host/aaa?b=1'
  - curl -skL 'https://msk.local.host' | grep -q 'vk.com/subscity_msk'
  - curl -skL 'https://msk.local.host/stylesheets/design.css' | grep -q 'color'
  - curl -skL 'https://spb.local.host/javascripts/default.min.js' | grep -q 'function'
  - curl -skIL 'http://local.host' | grep -q 'https://msk.local.host/'
  - curl -skIL 'https://local.host' | grep -q 'https://msk.local.host/'

after_script:
  - docker-compose stop

after_success:
  - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
  - docker tag subscity ${IMAGE_NAME}
  - docker push ${IMAGE_NAME}
